-- BlockQuest Classroom: learning event log
-- Run this once in Supabase SQL Editor.
-- Safe to run more than once.
create table if not exists public.learning_events (
  id bigint generated by default as identity primary key,
  player_name text not null,
  grade_id text,
  course_key text,
  unit_key text,
  activity text not null default 'quiz',
  correct boolean not null default false,
  first_try boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists learning_events_player_created_idx
  on public.learning_events (player_name, created_at desc);

alter table public.learning_events enable row level security;

-- The current BlockQuest client uses a public publishable key and name+PIN
-- accounts. Do not expose service-role keys in the browser.
-- These policies allow the current client to insert/read its event log.
drop policy if exists "learning_events_public_insert" on public.learning_events;
create policy "learning_events_public_insert"
  on public.learning_events for insert
  to anon, authenticated
  with check (true);

drop policy if exists "learning_events_public_select" on public.learning_events;
create policy "learning_events_public_select"
  on public.learning_events for select
  to anon, authenticated
  using (true);
